### ISSUE TITLE
Fatal error: Class 'Dotenv\Dotenv' not found in /var/www/html/application/libraries/Env.php on line 12

### ISSUE THREAD

**Issue by johnadan** [technoknol/env-in-CodeIgniter#4]
I followed the instructions but still can't make it work and displays this error

`Fatal error: Class 'Dotenv\Dotenv' not found in /var/www/html/application/libraries/Env.php on line 12`

even if vlucas\phpdotenv was successfully installed via composer.

Been stuck in this since last week.

Anyone knows how to fix this?

**Comment by athallarizky** [comment]
Yeah me too, I face the same problem.

**Comment by athallarizky** [comment]
Hey, I already fix it. With this step:

1. Change this to TRUE at config.php: 
      $config['enable_hooks'] = TRUE;
      $config['composer_autoload'] = TRUE;

2. Move your composer.json into "application" folder.

3. Run this composer command at "application" folder:
       - composer install
       - composer update
       - composer dump-autoload

note : .env file located in my root directory.

By the way, I just downgrade my package to "vlucas/phpdotenv": "^3.6". Because that I found in internets current version ( 4 ) use **$dotenv = Dotenv\Dotenv::createImmutable(__DIR__);** at Env.php file.

**Comment by johnadan** [comment]
> Hey, I already fix it. With this step:
> 
> 1. Change this to TRUE at config.php:
>    $config['enable_hooks'] = TRUE;
>    $config['composer_autoload'] = TRUE;
> 2. Move your composer.json into "application" folder.
> 3. Run this composer command at "application" folder:
>    - composer install
>    - composer update
>    - composer dump-autoload
> 
> note : .env file located in my root directory.
> 
> By the way, I just downgrade my package to "vlucas/phpdotenv": "^3.6". Because that I found in internets current version ( 4 ) use **$dotenv = Dotenv\Dotenv::createImmutable(**DIR**);** at Env.php file.

Hello! Will try this fix. Thanks!

**Comment by technoknol** [comment]
@johnadan Due to a bug in CodeIgniter setting `$config['composer_autoload'] = TRUE` will load `autoload.php` file from `application/vendor/autoload.php` which is not correct path. 

To fix this set config variable like below, unless you have vendor folder somewhere else than in project root. 
```
$config['composer_autoload'] = FCPATH. 'vendor'. DIRECTORY_SEPARATOR . 'autoload.php';
```

I've updated repo as well.
